sonata_admin:
    title_logo: /logo/vivitool-logo.png
    title: 'Vivitool'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        layout: 'admin/layout.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
