<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20231124095952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE besoins (id INT AUTO_INCREMENT NOT NULL, positionnement_concurrentiel_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, deleted INT NOT NULL, INDEX IDX_713FF7117E25F747 (positionnement_concurrentiel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE busines_model (id INT AUTO_INCREMENT NOT NULL, projet_id INT DEFAULT NULL, segment_client LONGTEXT DEFAULT NULL, proposition_valeur LONGTEXT DEFAULT NULL, canaux_distribution LONGTEXT DEFAULT NULL, flux_revenus LONGTEXT DEFAULT NULL, resource_cles LONGTEXT DEFAULT NULL, activite_cles LONGTEXT DEFAULT NULL, partnaire_stratedique LONGTEXT DEFAULT NULL, structure_couts LONGTEXT DEFAULT NULL, relation_client LONGTEXT DEFAULT NULL, avancement INT NOT NULL, lase_update DATE DEFAULT NULL, UNIQUE INDEX UNIQ_AA45C582C18272 (projet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE business_plan (id INT AUTO_INCREMENT NOT NULL, projet_id INT DEFAULT NULL, histoire_et_equipe_id INT DEFAULT NULL, financement_et_charges_id INT DEFAULT NULL, marche_et_concurrence_id INT DEFAULT NULL, positionnement_concurrentiel_id INT DEFAULT NULL, avancement INT NOT NULL, laste_update DATE DEFAULT NULL, UNIQUE INDEX UNIQ_8DC15970C18272 (projet_id), UNIQUE INDEX UNIQ_8DC159702DA6BAD8 (histoire_et_equipe_id), UNIQUE INDEX UNIQ_8DC159706E280150 (financement_et_charges_id), UNIQUE INDEX UNIQ_8DC15970824D36E2 (marche_et_concurrence_id), UNIQUE INDEX UNIQ_8DC159707E25F747 (positionnement_concurrentiel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cgu (id INT AUTO_INCREMENT NOT NULL, text LONGTEXT NOT NULL, titre VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cgv (id INT AUTO_INCREMENT NOT NULL, text LONGTEXT NOT NULL, titre VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE charge_ext (id INT AUTO_INCREMENT NOT NULL, depenses_id INT DEFAULT NULL, financement_et_charges_id INT DEFAULT NULL, financement_depense_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, deleted INT NOT NULL, INDEX IDX_708802A5338B55D2 (depenses_id), INDEX IDX_708802A56E280150 (financement_et_charges_id), INDEX IDX_708802A57A187140 (financement_depense_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE chiffre_affaire_activite (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, financement_chiffre_affaire_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, deleted INT NOT NULL, INDEX IDX_71443F816E280150 (financement_et_charges_id), INDEX IDX_71443F81524CFA4E (financement_chiffre_affaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE code_promos_subscription (id INT AUTO_INCREMENT NOT NULL, created_at DATE NOT NULL, name VARCHAR(255) NOT NULL, start DATE NOT NULL, end DATE NOT NULL, qte INT NOT NULL, reduce DOUBLE PRECISION NOT NULL, stripe_coupon VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE collaborateur_projet (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, projet_id INT DEFAULT NULL, firstename VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, page_permission LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', deleted INT NOT NULL, logo LONGTEXT DEFAULT NULL, tele VARCHAR(255) DEFAULT NULL, diplome VARCHAR(255) DEFAULT NULL, role VARCHAR(255) DEFAULT NULL, caracteristique VARCHAR(255) DEFAULT NULL, date_creation DATETIME DEFAULT NULL, dirigeant TINYINT(1) NOT NULL, is_salarie TINYINT(1) NOT NULL, equipe TINYINT(1) NOT NULL, INDEX IDX_6D1DC4D8A76ED395 (user_id), INDEX IDX_6D1DC4D8C18272 (projet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE collaborateur_projet_salaire_etcharge_social (collaborateur_projet_id INT NOT NULL, salaire_etcharge_social_id INT NOT NULL, INDEX IDX_BE02E94294BDF46 (collaborateur_projet_id), INDEX IDX_BE02E94BAA650F0 (salaire_etcharge_social_id), PRIMARY KEY(collaborateur_projet_id, salaire_etcharge_social_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE concurrents (id INT AUTO_INCREMENT NOT NULL, besoins_id INT DEFAULT NULL, societe_id INT DEFAULT NULL, positionnement_concurrentiel_id INT DEFAULT NULL, volume INT NOT NULL, INDEX IDX_FFDE7EC0963E5641 (besoins_id), INDEX IDX_FFDE7EC0FCF77503 (societe_id), INDEX IDX_FFDE7EC07E25F747 (positionnement_concurrentiel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cookies (id INT AUTO_INCREMENT NOT NULL, text LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE depenses (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE email_statistics (id INT AUTO_INCREMENT NOT NULL, nbre INT NOT NULL, created_at DATETIME NOT NULL, object VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, type_envoi VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE encaisse_decaissement (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, financement_encaisse_decaissement_id INT DEFAULT NULL, projet_annees_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, deleted INT NOT NULL, INDEX IDX_12F0F0C06E280150 (financement_et_charges_id), INDEX IDX_12F0F0C07A4FB940 (financement_encaisse_decaissement_id), INDEX IDX_12F0F0C079669628 (projet_annees_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faq (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financement_chiffre_affaire (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, avancement INT DEFAULT NULL, UNIQUE INDEX UNIQ_3B59030A6E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financement_depense (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, avancement INT DEFAULT NULL, UNIQUE INDEX UNIQ_A25FD9F6E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financement_encaisse_decaissement (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, avancement INT DEFAULT NULL, UNIQUE INDEX UNIQ_B5E2F17F6E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financement_et_charges (id INT AUTO_INCREMENT NOT NULL, charge_personnel LONGTEXT DEFAULT NULL, investissement LONGTEXT DEFAULT NULL, financement LONGTEXT DEFAULT NULL, synthese_prevesionnel LONGTEXT DEFAULT NULL, avanecement INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financement_investissement (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, avancement INT DEFAULT NULL, UNIQUE INDEX UNIQ_3F4E13476E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE histoire_et_equipe (id INT AUTO_INCREMENT NOT NULL, partenaire LONGTEXT DEFAULT NULL, secteur LONGTEXT DEFAULT NULL, tendance LONGTEXT DEFAULT NULL, cible LONGTEXT DEFAULT NULL, presentation_societe LONGTEXT DEFAULT NULL, avancement INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE info_bilan (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, projet_annees_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, valeur DOUBLE PRECISION NOT NULL, INDEX IDX_FE868AB16E280150 (financement_et_charges_id), INDEX IDX_FE868AB179669628 (projet_annees_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE instance (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, reference VARCHAR(255) NOT NULL, date_creation DATETIME NOT NULL, UNIQUE INDEX UNIQ_4230B1DEA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE investissement (id INT AUTO_INCREMENT NOT NULL, projet_annees_id INT DEFAULT NULL, financement_investissement_id INT DEFAULT NULL, investissement_nature_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, nature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, apport_en_nature VARCHAR(255) NOT NULL, deleted INT NOT NULL, INDEX IDX_B8E64E0179669628 (projet_annees_id), INDEX IDX_B8E64E01E31F734F (financement_investissement_id), INDEX IDX_B8E64E01D9E011DC (investissement_nature_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE investissement_montant (id INT AUTO_INCREMENT NOT NULL, investissement_id INT DEFAULT NULL, financement_investissement_id INT DEFAULT NULL, montant DOUBLE PRECISION DEFAULT NULL, UNIQUE INDEX UNIQ_E58FB7A540108A79 (investissement_id), INDEX IDX_E58FB7A5E31F734F (financement_investissement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE investissement_nature (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE marche_et_concurrence (id INT AUTO_INCREMENT NOT NULL, problem LONGTEXT DEFAULT NULL, avancement INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE montant_cext (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, deleted INT NOT NULL, INDEX IDX_565CF8C06E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE montant_cf (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, deleted INT NOT NULL, INDEX IDX_151958EE6E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE month_charge_ext (id INT AUTO_INCREMENT NOT NULL, charge_ext_id INT DEFAULT NULL, montant_cext_id INT DEFAULT NULL, projet_annees_id INT DEFAULT NULL, financement_depense_id INT DEFAULT NULL, jan DOUBLE PRECISION NOT NULL, frv DOUBLE PRECISION NOT NULL, mar DOUBLE PRECISION NOT NULL, avr DOUBLE PRECISION NOT NULL, mai DOUBLE PRECISION NOT NULL, juin DOUBLE PRECISION NOT NULL, juil DOUBLE PRECISION NOT NULL, aou DOUBLE PRECISION NOT NULL, sept DOUBLE PRECISION NOT NULL, oct DOUBLE PRECISION NOT NULL, nov DOUBLE PRECISION NOT NULL, dece DOUBLE PRECISION NOT NULL, volume DOUBLE PRECISION NOT NULL, deleted TINYINT(1) NOT NULL, INDEX IDX_A117978968A7335B (charge_ext_id), INDEX IDX_A11797894956254C (montant_cext_id), INDEX IDX_A117978979669628 (projet_annees_id), INDEX IDX_A11797897A187140 (financement_depense_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE month_liste_chiffre_affaire (id INT AUTO_INCREMENT NOT NULL, montant_cf_id INT DEFAULT NULL, chiffre_affaire_activite_id INT DEFAULT NULL, projet_annees_id INT DEFAULT NULL, financement_chiffre_affaire_id INT DEFAULT NULL, valeur DOUBLE PRECISION NOT NULL, jan_prix_ht DOUBLE PRECISION NOT NULL, jan_volume_vente DOUBLE PRECISION NOT NULL, fev_prix_ht DOUBLE PRECISION NOT NULL, frv_volume_vente DOUBLE PRECISION NOT NULL, mar_prix_ht DOUBLE PRECISION NOT NULL, mar_volume_vente DOUBLE PRECISION NOT NULL, avr_prix_ht DOUBLE PRECISION NOT NULL, avr_volume_vente DOUBLE PRECISION NOT NULL, mai_prix_ht DOUBLE PRECISION NOT NULL, mai_volume_vente DOUBLE PRECISION NOT NULL, juin_prix_ht DOUBLE PRECISION NOT NULL, juin_volume_vente DOUBLE PRECISION NOT NULL, juil_prix_ht DOUBLE PRECISION NOT NULL, juil_volume_vente DOUBLE PRECISION NOT NULL, aou_prix_ht DOUBLE PRECISION NOT NULL, aou_volume_vente DOUBLE PRECISION NOT NULL, sept_prix_ht DOUBLE PRECISION NOT NULL, sept_volume_vente DOUBLE PRECISION NOT NULL, oct_prix_ht DOUBLE PRECISION NOT NULL, oct_volume_vente DOUBLE PRECISION NOT NULL, nov_prix_ht DOUBLE PRECISION NOT NULL, nov_volume_vonte DOUBLE PRECISION NOT NULL, dec_prix_ht DOUBLE PRECISION NOT NULL, dec_volume_vonte DOUBLE PRECISION NOT NULL, deleted TINYINT(1) NOT NULL, INDEX IDX_1D13244ED3344713 (montant_cf_id), INDEX IDX_1D13244EAFD91B43 (chiffre_affaire_activite_id), INDEX IDX_1D13244E79669628 (projet_annees_id), INDEX IDX_1D13244E524CFA4E (financement_chiffre_affaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE monthe_liste_encaisse_decaissement (id INT AUTO_INCREMENT NOT NULL, projet_annees_id INT DEFAULT NULL, encaisse_decaissement_id INT DEFAULT NULL, jan DOUBLE PRECISION NOT NULL, frv DOUBLE PRECISION NOT NULL, mar DOUBLE PRECISION NOT NULL, avr DOUBLE PRECISION NOT NULL, mai DOUBLE PRECISION NOT NULL, juin DOUBLE PRECISION NOT NULL, juil DOUBLE PRECISION NOT NULL, aou DOUBLE PRECISION NOT NULL, sept DOUBLE PRECISION NOT NULL, oct DOUBLE PRECISION NOT NULL, nov DOUBLE PRECISION NOT NULL, dece DOUBLE PRECISION NOT NULL, INDEX IDX_EEFBF6A79669628 (projet_annees_id), UNIQUE INDEX UNIQ_EEFBF6A5EEF40C3 (encaisse_decaissement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notre_solution (id INT AUTO_INCREMENT NOT NULL, business_plan_id INT DEFAULT NULL, avancement INT NOT NULL, UNIQUE INDEX UNIQ_5E484A9DB5AAB9D6 (business_plan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partenaires (id INT AUTO_INCREMENT NOT NULL, nom_societe VARCHAR(255) DEFAULT NULL, site_web VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, service VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, secteur_activite VARCHAR(255) DEFAULT NULL, logo LONGTEXT DEFAULT NULL, photo_couvert LONGTEXT DEFAULT NULL, deleted INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE plan_financement_info (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, projet_annees_id INT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, value DOUBLE PRECISION DEFAULT NULL, INDEX IDX_805194CD6E280150 (financement_et_charges_id), INDEX IDX_805194CD79669628 (projet_annees_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE politique_confidentialite (id INT AUTO_INCREMENT NOT NULL, text LONGTEXT NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE popup_pub_front (id INT AUTO_INCREMENT NOT NULL, ville_id INT DEFAULT NULL, start DATE NOT NULL, end DATE NOT NULL, photo VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_76DDC9E6A73F0036 (ville_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE positionnement_concurrentiel (id INT AUTO_INCREMENT NOT NULL, avancement INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE projet (id INT AUTO_INCREMENT NOT NULL, instance_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, date_creation DATETIME NOT NULL, deleted INT NOT NULL, couleur_principal VARCHAR(255) DEFAULT NULL, couleur_secondaire VARCHAR(255) DEFAULT NULL, couleur_menu VARCHAR(255) DEFAULT NULL, slogan VARCHAR(255) NOT NULL, adress_siege_social VARCHAR(255) NOT NULL, siret VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(255) NOT NULL, logo LONGTEXT DEFAULT NULL, INDEX IDX_50159CA93A51721D (instance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE projet_annees (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, salaire_etcharge_social_id INT DEFAULT NULL, salaire_etcharge_social_dirigents_id INT DEFAULT NULL, financement_encaisse_decaissement_id INT DEFAULT NULL, financement_investissement_id INT DEFAULT NULL, financement_chiffre_affaire_id INT DEFAULT NULL, financement_depense_id INT DEFAULT NULL, projet_id INT DEFAULT NULL, notre_solution_id INT DEFAULT NULL, vision_strategies_for_business_plan_id INT DEFAULT NULL, annee VARCHAR(255) NOT NULL, deleted INT NOT NULL, INDEX IDX_32A232B96E280150 (financement_et_charges_id), UNIQUE INDEX UNIQ_32A232B9BAA650F0 (salaire_etcharge_social_id), UNIQUE INDEX UNIQ_32A232B9E372845A (salaire_etcharge_social_dirigents_id), INDEX IDX_32A232B97A4FB940 (financement_encaisse_decaissement_id), INDEX IDX_32A232B9E31F734F (financement_investissement_id), INDEX IDX_32A232B9524CFA4E (financement_chiffre_affaire_id), INDEX IDX_32A232B97A187140 (financement_depense_id), INDEX IDX_32A232B9C18272 (projet_id), INDEX IDX_32A232B9E11B80E0 (notre_solution_id), INDEX IDX_32A232B9D3E04EBF (vision_strategies_for_business_plan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE projet_annees_solution (projet_annees_id INT NOT NULL, solution_id INT NOT NULL, INDEX IDX_B5A2A9C79669628 (projet_annees_id), INDEX IDX_B5A2A9C1C0BE183 (solution_id), PRIMARY KEY(projet_annees_id, solution_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rendez_vous (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE revenus (id INT AUTO_INCREMENT NOT NULL, solution_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, prix_vente_ht DOUBLE PRECISION NOT NULL, volume_vente DOUBLE PRECISION NOT NULL, INDEX IDX_1DC5D9D41C0BE183 (solution_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salaire_etcharge_collaborateur_info (id INT AUTO_INCREMENT NOT NULL, collaborateur_projet_id INT DEFAULT NULL, salaire_etcharge_social_id INT DEFAULT NULL, financement_et_charges_id INT DEFAULT NULL, salaire_brut DOUBLE PRECISION DEFAULT NULL, type_contrat VARCHAR(255) DEFAULT NULL, charge_social DOUBLE PRECISION DEFAULT NULL, INDEX IDX_317C1C72294BDF46 (collaborateur_projet_id), INDEX IDX_317C1C72BAA650F0 (salaire_etcharge_social_id), INDEX IDX_317C1C726E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salaire_etcharge_dirigents_info (id INT AUTO_INCREMENT NOT NULL, salaire_etcharge_social_dirigents_id INT DEFAULT NULL, collaborateur_projet_id INT DEFAULT NULL, financement_et_charges_id INT DEFAULT NULL, pourcentage_participation_capital INT DEFAULT NULL, reparation_renumeratin_annee DOUBLE PRECISION DEFAULT NULL, beneficier VARCHAR(255) NOT NULL, INDEX IDX_126DCB63E372845A (salaire_etcharge_social_dirigents_id), INDEX IDX_126DCB63294BDF46 (collaborateur_projet_id), INDEX IDX_126DCB636E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salaire_etcharge_social (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, deleted INT NOT NULL, INDEX IDX_38E7F5D56E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salaire_etcharge_social_dirigents (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, deleted INT NOT NULL, INDEX IDX_A18E92BC6E280150 (financement_et_charges_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salaire_etcharge_social_dirigents_collaborateur_projet (salaire_etcharge_social_dirigents_id INT NOT NULL, collaborateur_projet_id INT NOT NULL, INDEX IDX_5AA256A4E372845A (salaire_etcharge_social_dirigents_id), INDEX IDX_5AA256A4294BDF46 (collaborateur_projet_id), PRIMARY KEY(salaire_etcharge_social_dirigents_id, collaborateur_projet_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content VARCHAR(255) DEFAULT NULL, canonical VARCHAR(255) DEFAULT NULL, meta_title VARCHAR(255) DEFAULT NULL, robots VARCHAR(255) DEFAULT NULL, meta_desc VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, url VARCHAR(255) NOT NULL, updated DATETIME NOT NULL, og_title VARCHAR(255) NOT NULL, og_description VARCHAR(255) NOT NULL, keyword VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting_seo (id INT AUTO_INCREMENT NOT NULL, hotjar LONGTEXT NOT NULL, google_analytics LONGTEXT NOT NULL, pixel_facebook LONGTEXT NOT NULL, pixel_tiktok LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sms_statistics (id INT AUTO_INCREMENT NOT NULL, nbre INT NOT NULL, created_at DATETIME NOT NULL, message LONGTEXT NOT NULL, type_envoie VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE societe (id INT AUTO_INCREMENT NOT NULL, marche_et_concurrence_id INT DEFAULT NULL, positionnement_concurrentiel_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, point_fort LONGTEXT DEFAULT NULL, point_faible LONGTEXT DEFAULT NULL, direct_indirect VARCHAR(255) DEFAULT NULL, taille VARCHAR(255) DEFAULT NULL, effectif VARCHAR(255) DEFAULT NULL, ca VARCHAR(255) DEFAULT NULL, deleted VARCHAR(255) NOT NULL, logo LONGTEXT DEFAULT NULL, avancement INT NOT NULL, INDEX IDX_19653DBD824D36E2 (marche_et_concurrence_id), INDEX IDX_19653DBD7E25F747 (positionnement_concurrentiel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE solution (id INT AUTO_INCREMENT NOT NULL, notre_solution_id INT DEFAULT NULL, innovation LONGTEXT DEFAULT NULL, point_fort LONGTEXT DEFAULT NULL, desc_technique LONGTEXT DEFAULT NULL, deleted INT NOT NULL, name VARCHAR(255) NOT NULL, avancement INT NOT NULL, INDEX IDX_9F3329DBE11B80E0 (notre_solution_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE strategie (id INT AUTO_INCREMENT NOT NULL, debut DATE DEFAULT NULL, fin DATE DEFAULT NULL, action VARCHAR(255) DEFAULT NULL, cible VARCHAR(255) DEFAULT NULL, cout DOUBLE PRECISION DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tresorerie_info (id INT AUTO_INCREMENT NOT NULL, financement_et_charges_id INT DEFAULT NULL, projet_annees_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, jan DOUBLE PRECISION NOT NULL, frv DOUBLE PRECISION NOT NULL, mar DOUBLE PRECISION NOT NULL, avr DOUBLE PRECISION NOT NULL, mai DOUBLE PRECISION NOT NULL, juin DOUBLE PRECISION NOT NULL, juil DOUBLE PRECISION NOT NULL, aou DOUBLE PRECISION NOT NULL, sept DOUBLE PRECISION NOT NULL, oct DOUBLE PRECISION NOT NULL, nov DOUBLE PRECISION NOT NULL, dece DOUBLE PRECISION NOT NULL, INDEX IDX_CF72B55A6E280150 (financement_et_charges_id), INDEX IDX_CF72B55A79669628 (projet_annees_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, username VARCHAR(255) DEFAULT NULL, token VARCHAR(255) NOT NULL, date_creation DATETIME NOT NULL, phone VARCHAR(255) DEFAULT NULL, photo_profil LONGTEXT DEFAULT NULL, tele VARCHAR(255) DEFAULT NULL, diplome VARCHAR(255) DEFAULT NULL, role VARCHAR(255) DEFAULT NULL, caracteristique VARCHAR(255) DEFAULT NULL, token_securite VARCHAR(255) DEFAULT NULL, deleted TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ville (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, photo VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vision_strategies (id INT AUTO_INCREMENT NOT NULL, action_id INT DEFAULT NULL, objectif_id INT DEFAULT NULL, cout_id INT DEFAULT NULL, vision_strategies_for_business_plan_id INT DEFAULT NULL, projet_annees_id INT DEFAULT NULL, avancement INT NOT NULL, date_vision_strategies DATE NOT NULL, deleted INT NOT NULL, UNIQUE INDEX UNIQ_5ACC18D99D32F035 (action_id), UNIQUE INDEX UNIQ_5ACC18D9157D1AD4 (objectif_id), UNIQUE INDEX UNIQ_5ACC18D992FF70DF (cout_id), INDEX IDX_5ACC18D9D3E04EBF (vision_strategies_for_business_plan_id), INDEX IDX_5ACC18D979669628 (projet_annees_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vision_strategies_for_business_plan (id INT AUTO_INCREMENT NOT NULL, business_plan_id INT DEFAULT NULL, avancement INT NOT NULL, UNIQUE INDEX UNIQ_34F01357B5AAB9D6 (business_plan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE besoins ADD CONSTRAINT FK_713FF7117E25F747 FOREIGN KEY (positionnement_concurrentiel_id) REFERENCES positionnement_concurrentiel (id)');
        $this->addSql('ALTER TABLE busines_model ADD CONSTRAINT FK_AA45C582C18272 FOREIGN KEY (projet_id) REFERENCES projet (id)');
        $this->addSql('ALTER TABLE business_plan ADD CONSTRAINT FK_8DC15970C18272 FOREIGN KEY (projet_id) REFERENCES projet (id)');
        $this->addSql('ALTER TABLE business_plan ADD CONSTRAINT FK_8DC159702DA6BAD8 FOREIGN KEY (histoire_et_equipe_id) REFERENCES histoire_et_equipe (id)');
        $this->addSql('ALTER TABLE business_plan ADD CONSTRAINT FK_8DC159706E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE business_plan ADD CONSTRAINT FK_8DC15970824D36E2 FOREIGN KEY (marche_et_concurrence_id) REFERENCES marche_et_concurrence (id)');
        $this->addSql('ALTER TABLE business_plan ADD CONSTRAINT FK_8DC159707E25F747 FOREIGN KEY (positionnement_concurrentiel_id) REFERENCES positionnement_concurrentiel (id)');
        $this->addSql('ALTER TABLE charge_ext ADD CONSTRAINT FK_708802A5338B55D2 FOREIGN KEY (depenses_id) REFERENCES depenses (id)');
        $this->addSql('ALTER TABLE charge_ext ADD CONSTRAINT FK_708802A56E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE charge_ext ADD CONSTRAINT FK_708802A57A187140 FOREIGN KEY (financement_depense_id) REFERENCES financement_depense (id)');
        $this->addSql('ALTER TABLE chiffre_affaire_activite ADD CONSTRAINT FK_71443F816E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE chiffre_affaire_activite ADD CONSTRAINT FK_71443F81524CFA4E FOREIGN KEY (financement_chiffre_affaire_id) REFERENCES financement_chiffre_affaire (id)');
        $this->addSql('ALTER TABLE collaborateur_projet ADD CONSTRAINT FK_6D1DC4D8A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE collaborateur_projet ADD CONSTRAINT FK_6D1DC4D8C18272 FOREIGN KEY (projet_id) REFERENCES projet (id)');
        $this->addSql('ALTER TABLE collaborateur_projet_salaire_etcharge_social ADD CONSTRAINT FK_BE02E94294BDF46 FOREIGN KEY (collaborateur_projet_id) REFERENCES collaborateur_projet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE collaborateur_projet_salaire_etcharge_social ADD CONSTRAINT FK_BE02E94BAA650F0 FOREIGN KEY (salaire_etcharge_social_id) REFERENCES salaire_etcharge_social (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE concurrents ADD CONSTRAINT FK_FFDE7EC0963E5641 FOREIGN KEY (besoins_id) REFERENCES besoins (id)');
        $this->addSql('ALTER TABLE concurrents ADD CONSTRAINT FK_FFDE7EC0FCF77503 FOREIGN KEY (societe_id) REFERENCES societe (id)');
        $this->addSql('ALTER TABLE concurrents ADD CONSTRAINT FK_FFDE7EC07E25F747 FOREIGN KEY (positionnement_concurrentiel_id) REFERENCES positionnement_concurrentiel (id)');
        $this->addSql('ALTER TABLE encaisse_decaissement ADD CONSTRAINT FK_12F0F0C06E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE encaisse_decaissement ADD CONSTRAINT FK_12F0F0C07A4FB940 FOREIGN KEY (financement_encaisse_decaissement_id) REFERENCES financement_encaisse_decaissement (id)');
        $this->addSql('ALTER TABLE encaisse_decaissement ADD CONSTRAINT FK_12F0F0C079669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id)');
        $this->addSql('ALTER TABLE financement_chiffre_affaire ADD CONSTRAINT FK_3B59030A6E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE financement_depense ADD CONSTRAINT FK_A25FD9F6E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE financement_encaisse_decaissement ADD CONSTRAINT FK_B5E2F17F6E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE financement_investissement ADD CONSTRAINT FK_3F4E13476E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE info_bilan ADD CONSTRAINT FK_FE868AB16E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE info_bilan ADD CONSTRAINT FK_FE868AB179669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id)');
        $this->addSql('ALTER TABLE instance ADD CONSTRAINT FK_4230B1DEA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE investissement ADD CONSTRAINT FK_B8E64E0179669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id)');
        $this->addSql('ALTER TABLE investissement ADD CONSTRAINT FK_B8E64E01E31F734F FOREIGN KEY (financement_investissement_id) REFERENCES financement_investissement (id)');
        $this->addSql('ALTER TABLE investissement ADD CONSTRAINT FK_B8E64E01D9E011DC FOREIGN KEY (investissement_nature_id) REFERENCES investissement_nature (id)');
        $this->addSql('ALTER TABLE investissement_montant ADD CONSTRAINT FK_E58FB7A540108A79 FOREIGN KEY (investissement_id) REFERENCES investissement (id)');
        $this->addSql('ALTER TABLE investissement_montant ADD CONSTRAINT FK_E58FB7A5E31F734F FOREIGN KEY (financement_investissement_id) REFERENCES financement_investissement (id)');
        $this->addSql('ALTER TABLE montant_cext ADD CONSTRAINT FK_565CF8C06E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE montant_cf ADD CONSTRAINT FK_151958EE6E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE month_charge_ext ADD CONSTRAINT FK_A117978968A7335B FOREIGN KEY (charge_ext_id) REFERENCES charge_ext (id)');
        $this->addSql('ALTER TABLE month_charge_ext ADD CONSTRAINT FK_A11797894956254C FOREIGN KEY (montant_cext_id) REFERENCES montant_cext (id)');
        $this->addSql('ALTER TABLE month_charge_ext ADD CONSTRAINT FK_A117978979669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id)');
        $this->addSql('ALTER TABLE month_charge_ext ADD CONSTRAINT FK_A11797897A187140 FOREIGN KEY (financement_depense_id) REFERENCES financement_depense (id)');
        $this->addSql('ALTER TABLE month_liste_chiffre_affaire ADD CONSTRAINT FK_1D13244ED3344713 FOREIGN KEY (montant_cf_id) REFERENCES montant_cf (id)');
        $this->addSql('ALTER TABLE month_liste_chiffre_affaire ADD CONSTRAINT FK_1D13244EAFD91B43 FOREIGN KEY (chiffre_affaire_activite_id) REFERENCES chiffre_affaire_activite (id)');
        $this->addSql('ALTER TABLE month_liste_chiffre_affaire ADD CONSTRAINT FK_1D13244E79669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id)');
        $this->addSql('ALTER TABLE month_liste_chiffre_affaire ADD CONSTRAINT FK_1D13244E524CFA4E FOREIGN KEY (financement_chiffre_affaire_id) REFERENCES financement_chiffre_affaire (id)');
        $this->addSql('ALTER TABLE monthe_liste_encaisse_decaissement ADD CONSTRAINT FK_EEFBF6A79669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id)');
        $this->addSql('ALTER TABLE monthe_liste_encaisse_decaissement ADD CONSTRAINT FK_EEFBF6A5EEF40C3 FOREIGN KEY (encaisse_decaissement_id) REFERENCES encaisse_decaissement (id)');
        $this->addSql('ALTER TABLE notre_solution ADD CONSTRAINT FK_5E484A9DB5AAB9D6 FOREIGN KEY (business_plan_id) REFERENCES business_plan (id)');
        $this->addSql('ALTER TABLE plan_financement_info ADD CONSTRAINT FK_805194CD6E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE plan_financement_info ADD CONSTRAINT FK_805194CD79669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id)');
        $this->addSql('ALTER TABLE popup_pub_front ADD CONSTRAINT FK_76DDC9E6A73F0036 FOREIGN KEY (ville_id) REFERENCES ville (id)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA93A51721D FOREIGN KEY (instance_id) REFERENCES instance (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B96E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B9BAA650F0 FOREIGN KEY (salaire_etcharge_social_id) REFERENCES salaire_etcharge_social (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B9E372845A FOREIGN KEY (salaire_etcharge_social_dirigents_id) REFERENCES salaire_etcharge_social_dirigents (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B97A4FB940 FOREIGN KEY (financement_encaisse_decaissement_id) REFERENCES financement_encaisse_decaissement (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B9E31F734F FOREIGN KEY (financement_investissement_id) REFERENCES financement_investissement (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B9524CFA4E FOREIGN KEY (financement_chiffre_affaire_id) REFERENCES financement_chiffre_affaire (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B97A187140 FOREIGN KEY (financement_depense_id) REFERENCES financement_depense (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B9C18272 FOREIGN KEY (projet_id) REFERENCES projet (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B9E11B80E0 FOREIGN KEY (notre_solution_id) REFERENCES notre_solution (id)');
        $this->addSql('ALTER TABLE projet_annees ADD CONSTRAINT FK_32A232B9D3E04EBF FOREIGN KEY (vision_strategies_for_business_plan_id) REFERENCES vision_strategies_for_business_plan (id)');
        $this->addSql('ALTER TABLE projet_annees_solution ADD CONSTRAINT FK_B5A2A9C79669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projet_annees_solution ADD CONSTRAINT FK_B5A2A9C1C0BE183 FOREIGN KEY (solution_id) REFERENCES solution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE revenus ADD CONSTRAINT FK_1DC5D9D41C0BE183 FOREIGN KEY (solution_id) REFERENCES solution (id)');
        $this->addSql('ALTER TABLE salaire_etcharge_collaborateur_info ADD CONSTRAINT FK_317C1C72294BDF46 FOREIGN KEY (collaborateur_projet_id) REFERENCES collaborateur_projet (id)');
        $this->addSql('ALTER TABLE salaire_etcharge_collaborateur_info ADD CONSTRAINT FK_317C1C72BAA650F0 FOREIGN KEY (salaire_etcharge_social_id) REFERENCES salaire_etcharge_social (id)');
        $this->addSql('ALTER TABLE salaire_etcharge_collaborateur_info ADD CONSTRAINT FK_317C1C726E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE salaire_etcharge_dirigents_info ADD CONSTRAINT FK_126DCB63E372845A FOREIGN KEY (salaire_etcharge_social_dirigents_id) REFERENCES salaire_etcharge_social_dirigents (id)');
        $this->addSql('ALTER TABLE salaire_etcharge_dirigents_info ADD CONSTRAINT FK_126DCB63294BDF46 FOREIGN KEY (collaborateur_projet_id) REFERENCES collaborateur_projet (id)');
        $this->addSql('ALTER TABLE salaire_etcharge_dirigents_info ADD CONSTRAINT FK_126DCB636E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE salaire_etcharge_social ADD CONSTRAINT FK_38E7F5D56E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE salaire_etcharge_social_dirigents ADD CONSTRAINT FK_A18E92BC6E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE salaire_etcharge_social_dirigents_collaborateur_projet ADD CONSTRAINT FK_5AA256A4E372845A FOREIGN KEY (salaire_etcharge_social_dirigents_id) REFERENCES salaire_etcharge_social_dirigents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE salaire_etcharge_social_dirigents_collaborateur_projet ADD CONSTRAINT FK_5AA256A4294BDF46 FOREIGN KEY (collaborateur_projet_id) REFERENCES collaborateur_projet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE societe ADD CONSTRAINT FK_19653DBD824D36E2 FOREIGN KEY (marche_et_concurrence_id) REFERENCES marche_et_concurrence (id)');
        $this->addSql('ALTER TABLE societe ADD CONSTRAINT FK_19653DBD7E25F747 FOREIGN KEY (positionnement_concurrentiel_id) REFERENCES positionnement_concurrentiel (id)');
        $this->addSql('ALTER TABLE solution ADD CONSTRAINT FK_9F3329DBE11B80E0 FOREIGN KEY (notre_solution_id) REFERENCES notre_solution (id)');
        $this->addSql('ALTER TABLE tresorerie_info ADD CONSTRAINT FK_CF72B55A6E280150 FOREIGN KEY (financement_et_charges_id) REFERENCES financement_et_charges (id)');
        $this->addSql('ALTER TABLE tresorerie_info ADD CONSTRAINT FK_CF72B55A79669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id)');
        $this->addSql('ALTER TABLE vision_strategies ADD CONSTRAINT FK_5ACC18D99D32F035 FOREIGN KEY (action_id) REFERENCES strategie (id)');
        $this->addSql('ALTER TABLE vision_strategies ADD CONSTRAINT FK_5ACC18D9157D1AD4 FOREIGN KEY (objectif_id) REFERENCES strategie (id)');
        $this->addSql('ALTER TABLE vision_strategies ADD CONSTRAINT FK_5ACC18D992FF70DF FOREIGN KEY (cout_id) REFERENCES strategie (id)');
        $this->addSql('ALTER TABLE vision_strategies ADD CONSTRAINT FK_5ACC18D9D3E04EBF FOREIGN KEY (vision_strategies_for_business_plan_id) REFERENCES vision_strategies_for_business_plan (id)');
        $this->addSql('ALTER TABLE vision_strategies ADD CONSTRAINT FK_5ACC18D979669628 FOREIGN KEY (projet_annees_id) REFERENCES projet_annees (id)');
        $this->addSql('ALTER TABLE vision_strategies_for_business_plan ADD CONSTRAINT FK_34F01357B5AAB9D6 FOREIGN KEY (business_plan_id) REFERENCES business_plan (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE besoins DROP FOREIGN KEY FK_713FF7117E25F747');
        $this->addSql('ALTER TABLE busines_model DROP FOREIGN KEY FK_AA45C582C18272');
        $this->addSql('ALTER TABLE business_plan DROP FOREIGN KEY FK_8DC15970C18272');
        $this->addSql('ALTER TABLE business_plan DROP FOREIGN KEY FK_8DC159702DA6BAD8');
        $this->addSql('ALTER TABLE business_plan DROP FOREIGN KEY FK_8DC159706E280150');
        $this->addSql('ALTER TABLE business_plan DROP FOREIGN KEY FK_8DC15970824D36E2');
        $this->addSql('ALTER TABLE business_plan DROP FOREIGN KEY FK_8DC159707E25F747');
        $this->addSql('ALTER TABLE charge_ext DROP FOREIGN KEY FK_708802A5338B55D2');
        $this->addSql('ALTER TABLE charge_ext DROP FOREIGN KEY FK_708802A56E280150');
        $this->addSql('ALTER TABLE charge_ext DROP FOREIGN KEY FK_708802A57A187140');
        $this->addSql('ALTER TABLE chiffre_affaire_activite DROP FOREIGN KEY FK_71443F816E280150');
        $this->addSql('ALTER TABLE chiffre_affaire_activite DROP FOREIGN KEY FK_71443F81524CFA4E');
        $this->addSql('ALTER TABLE collaborateur_projet DROP FOREIGN KEY FK_6D1DC4D8A76ED395');
        $this->addSql('ALTER TABLE collaborateur_projet DROP FOREIGN KEY FK_6D1DC4D8C18272');
        $this->addSql('ALTER TABLE collaborateur_projet_salaire_etcharge_social DROP FOREIGN KEY FK_BE02E94294BDF46');
        $this->addSql('ALTER TABLE collaborateur_projet_salaire_etcharge_social DROP FOREIGN KEY FK_BE02E94BAA650F0');
        $this->addSql('ALTER TABLE concurrents DROP FOREIGN KEY FK_FFDE7EC0963E5641');
        $this->addSql('ALTER TABLE concurrents DROP FOREIGN KEY FK_FFDE7EC0FCF77503');
        $this->addSql('ALTER TABLE concurrents DROP FOREIGN KEY FK_FFDE7EC07E25F747');
        $this->addSql('ALTER TABLE encaisse_decaissement DROP FOREIGN KEY FK_12F0F0C06E280150');
        $this->addSql('ALTER TABLE encaisse_decaissement DROP FOREIGN KEY FK_12F0F0C07A4FB940');
        $this->addSql('ALTER TABLE encaisse_decaissement DROP FOREIGN KEY FK_12F0F0C079669628');
        $this->addSql('ALTER TABLE financement_chiffre_affaire DROP FOREIGN KEY FK_3B59030A6E280150');
        $this->addSql('ALTER TABLE financement_depense DROP FOREIGN KEY FK_A25FD9F6E280150');
        $this->addSql('ALTER TABLE financement_encaisse_decaissement DROP FOREIGN KEY FK_B5E2F17F6E280150');
        $this->addSql('ALTER TABLE financement_investissement DROP FOREIGN KEY FK_3F4E13476E280150');
        $this->addSql('ALTER TABLE info_bilan DROP FOREIGN KEY FK_FE868AB16E280150');
        $this->addSql('ALTER TABLE info_bilan DROP FOREIGN KEY FK_FE868AB179669628');
        $this->addSql('ALTER TABLE instance DROP FOREIGN KEY FK_4230B1DEA76ED395');
        $this->addSql('ALTER TABLE investissement DROP FOREIGN KEY FK_B8E64E0179669628');
        $this->addSql('ALTER TABLE investissement DROP FOREIGN KEY FK_B8E64E01E31F734F');
        $this->addSql('ALTER TABLE investissement DROP FOREIGN KEY FK_B8E64E01D9E011DC');
        $this->addSql('ALTER TABLE investissement_montant DROP FOREIGN KEY FK_E58FB7A540108A79');
        $this->addSql('ALTER TABLE investissement_montant DROP FOREIGN KEY FK_E58FB7A5E31F734F');
        $this->addSql('ALTER TABLE montant_cext DROP FOREIGN KEY FK_565CF8C06E280150');
        $this->addSql('ALTER TABLE montant_cf DROP FOREIGN KEY FK_151958EE6E280150');
        $this->addSql('ALTER TABLE month_charge_ext DROP FOREIGN KEY FK_A117978968A7335B');
        $this->addSql('ALTER TABLE month_charge_ext DROP FOREIGN KEY FK_A11797894956254C');
        $this->addSql('ALTER TABLE month_charge_ext DROP FOREIGN KEY FK_A117978979669628');
        $this->addSql('ALTER TABLE month_charge_ext DROP FOREIGN KEY FK_A11797897A187140');
        $this->addSql('ALTER TABLE month_liste_chiffre_affaire DROP FOREIGN KEY FK_1D13244ED3344713');
        $this->addSql('ALTER TABLE month_liste_chiffre_affaire DROP FOREIGN KEY FK_1D13244EAFD91B43');
        $this->addSql('ALTER TABLE month_liste_chiffre_affaire DROP FOREIGN KEY FK_1D13244E79669628');
        $this->addSql('ALTER TABLE month_liste_chiffre_affaire DROP FOREIGN KEY FK_1D13244E524CFA4E');
        $this->addSql('ALTER TABLE monthe_liste_encaisse_decaissement DROP FOREIGN KEY FK_EEFBF6A79669628');
        $this->addSql('ALTER TABLE monthe_liste_encaisse_decaissement DROP FOREIGN KEY FK_EEFBF6A5EEF40C3');
        $this->addSql('ALTER TABLE notre_solution DROP FOREIGN KEY FK_5E484A9DB5AAB9D6');
        $this->addSql('ALTER TABLE plan_financement_info DROP FOREIGN KEY FK_805194CD6E280150');
        $this->addSql('ALTER TABLE plan_financement_info DROP FOREIGN KEY FK_805194CD79669628');
        $this->addSql('ALTER TABLE popup_pub_front DROP FOREIGN KEY FK_76DDC9E6A73F0036');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_50159CA93A51721D');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B96E280150');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B9BAA650F0');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B9E372845A');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B97A4FB940');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B9E31F734F');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B9524CFA4E');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B97A187140');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B9C18272');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B9E11B80E0');
        $this->addSql('ALTER TABLE projet_annees DROP FOREIGN KEY FK_32A232B9D3E04EBF');
        $this->addSql('ALTER TABLE projet_annees_solution DROP FOREIGN KEY FK_B5A2A9C79669628');
        $this->addSql('ALTER TABLE projet_annees_solution DROP FOREIGN KEY FK_B5A2A9C1C0BE183');
        $this->addSql('ALTER TABLE revenus DROP FOREIGN KEY FK_1DC5D9D41C0BE183');
        $this->addSql('ALTER TABLE salaire_etcharge_collaborateur_info DROP FOREIGN KEY FK_317C1C72294BDF46');
        $this->addSql('ALTER TABLE salaire_etcharge_collaborateur_info DROP FOREIGN KEY FK_317C1C72BAA650F0');
        $this->addSql('ALTER TABLE salaire_etcharge_collaborateur_info DROP FOREIGN KEY FK_317C1C726E280150');
        $this->addSql('ALTER TABLE salaire_etcharge_dirigents_info DROP FOREIGN KEY FK_126DCB63E372845A');
        $this->addSql('ALTER TABLE salaire_etcharge_dirigents_info DROP FOREIGN KEY FK_126DCB63294BDF46');
        $this->addSql('ALTER TABLE salaire_etcharge_dirigents_info DROP FOREIGN KEY FK_126DCB636E280150');
        $this->addSql('ALTER TABLE salaire_etcharge_social DROP FOREIGN KEY FK_38E7F5D56E280150');
        $this->addSql('ALTER TABLE salaire_etcharge_social_dirigents DROP FOREIGN KEY FK_A18E92BC6E280150');
        $this->addSql('ALTER TABLE salaire_etcharge_social_dirigents_collaborateur_projet DROP FOREIGN KEY FK_5AA256A4E372845A');
        $this->addSql('ALTER TABLE salaire_etcharge_social_dirigents_collaborateur_projet DROP FOREIGN KEY FK_5AA256A4294BDF46');
        $this->addSql('ALTER TABLE societe DROP FOREIGN KEY FK_19653DBD824D36E2');
        $this->addSql('ALTER TABLE societe DROP FOREIGN KEY FK_19653DBD7E25F747');
        $this->addSql('ALTER TABLE solution DROP FOREIGN KEY FK_9F3329DBE11B80E0');
        $this->addSql('ALTER TABLE tresorerie_info DROP FOREIGN KEY FK_CF72B55A6E280150');
        $this->addSql('ALTER TABLE tresorerie_info DROP FOREIGN KEY FK_CF72B55A79669628');
        $this->addSql('ALTER TABLE vision_strategies DROP FOREIGN KEY FK_5ACC18D99D32F035');
        $this->addSql('ALTER TABLE vision_strategies DROP FOREIGN KEY FK_5ACC18D9157D1AD4');
        $this->addSql('ALTER TABLE vision_strategies DROP FOREIGN KEY FK_5ACC18D992FF70DF');
        $this->addSql('ALTER TABLE vision_strategies DROP FOREIGN KEY FK_5ACC18D9D3E04EBF');
        $this->addSql('ALTER TABLE vision_strategies DROP FOREIGN KEY FK_5ACC18D979669628');
        $this->addSql('ALTER TABLE vision_strategies_for_business_plan DROP FOREIGN KEY FK_34F01357B5AAB9D6');
        $this->addSql('DROP TABLE besoins');
        $this->addSql('DROP TABLE busines_model');
        $this->addSql('DROP TABLE business_plan');
        $this->addSql('DROP TABLE cgu');
        $this->addSql('DROP TABLE cgv');
        $this->addSql('DROP TABLE charge_ext');
        $this->addSql('DROP TABLE chiffre_affaire_activite');
        $this->addSql('DROP TABLE code_promos_subscription');
        $this->addSql('DROP TABLE collaborateur_projet');
        $this->addSql('DROP TABLE collaborateur_projet_salaire_etcharge_social');
        $this->addSql('DROP TABLE concurrents');
        $this->addSql('DROP TABLE cookies');
        $this->addSql('DROP TABLE depenses');
        $this->addSql('DROP TABLE email_statistics');
        $this->addSql('DROP TABLE encaisse_decaissement');
        $this->addSql('DROP TABLE faq');
        $this->addSql('DROP TABLE financement_chiffre_affaire');
        $this->addSql('DROP TABLE financement_depense');
        $this->addSql('DROP TABLE financement_encaisse_decaissement');
        $this->addSql('DROP TABLE financement_et_charges');
        $this->addSql('DROP TABLE financement_investissement');
        $this->addSql('DROP TABLE histoire_et_equipe');
        $this->addSql('DROP TABLE info_bilan');
        $this->addSql('DROP TABLE instance');
        $this->addSql('DROP TABLE investissement');
        $this->addSql('DROP TABLE investissement_montant');
        $this->addSql('DROP TABLE investissement_nature');
        $this->addSql('DROP TABLE marche_et_concurrence');
        $this->addSql('DROP TABLE montant_cext');
        $this->addSql('DROP TABLE montant_cf');
        $this->addSql('DROP TABLE month_charge_ext');
        $this->addSql('DROP TABLE month_liste_chiffre_affaire');
        $this->addSql('DROP TABLE monthe_liste_encaisse_decaissement');
        $this->addSql('DROP TABLE notre_solution');
        $this->addSql('DROP TABLE partenaires');
        $this->addSql('DROP TABLE plan_financement_info');
        $this->addSql('DROP TABLE politique_confidentialite');
        $this->addSql('DROP TABLE popup_pub_front');
        $this->addSql('DROP TABLE positionnement_concurrentiel');
        $this->addSql('DROP TABLE projet');
        $this->addSql('DROP TABLE projet_annees');
        $this->addSql('DROP TABLE projet_annees_solution');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE revenus');
        $this->addSql('DROP TABLE salaire_etcharge_collaborateur_info');
        $this->addSql('DROP TABLE salaire_etcharge_dirigents_info');
        $this->addSql('DROP TABLE salaire_etcharge_social');
        $this->addSql('DROP TABLE salaire_etcharge_social_dirigents');
        $this->addSql('DROP TABLE salaire_etcharge_social_dirigents_collaborateur_projet');
        $this->addSql('DROP TABLE seo');
        $this->addSql('DROP TABLE setting_seo');
        $this->addSql('DROP TABLE sms_statistics');
        $this->addSql('DROP TABLE societe');
        $this->addSql('DROP TABLE solution');
        $this->addSql('DROP TABLE strategie');
        $this->addSql('DROP TABLE tresorerie_info');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE ville');
        $this->addSql('DROP TABLE vision_strategies');
        $this->addSql('DROP TABLE vision_strategies_for_business_plan');
    }
}
