version: "3"
services:
    database:
        image: mysql
        container_name: vivitools-db-1
        restart: always
        command: --sql_mode=""
        volumes:
            - db-data-vivitools:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev-vivitools
    webpack:
        image: node:alpine
        volumes:
        - ./:/var/www/app:rw,cached
        working_dir: /var/www/app
        command: yarn encore dev --watch
    
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_vivitools-db-1
        restart: always
        depends_on:
            - database
        ports:
            - 8080:80
        environment:
            PMA_HOST: database
        networks:
            - dev-vivitools          
# PHP Service
    php:
        build: ./docker/php
        container_name: www_vivitools
        restart: unless-stopped
        working_dir: /var/www
        volumes:
        - ./:/var/www
        - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - dev-vivitools

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: vivitools_nginx
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - dev-vivitools
networks:
    dev-vivitools:

volumes:
    db-data-vivitools:

